/** @type {import('next').NextConfig} */
// Fully static build served by GitHub Pages — no server, no DB. Content comes
// from content/site-data.json (regenerated by the Drive sync) at build time.
// NEXT_PUBLIC_BASE_PATH ('' for the custom domain, '/<repo>' for the
// kdumanski.github.io/<repo> preview) must be set consistently: it feeds both
// Next's basePath and the img() prefix in lib/data.js.
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';

const nextConfig = {
  output: 'export',
  reactStrictMode: true,
  trailingSlash: true,
  ...(basePath ? { basePath } : {}),
};

export default nextConfig;
